### ISSUE TITLE
mute/remove print of recognized cases from get_eclfiles()

### ISSUE THREAD

**Issue by asnyv** [equinor/fmu-ensemble#122]
List of identified cases is printed for each realization if autodiscovery 
[here](https://github.com/equinor/fmu-ensemble/blob/999278d141362c17ff3dd1a33263a65d1eeff6b2/src/fmu/ensemble/realization.py#L905)
A warning is also written to the logger straight after if more than 1 file is found, therefore maybe not necessary to print each time? (think at least there should be a mute option)

**Comment by berland** [comment]
That looks like a leftover while-coding print statement.  Will be removed.
