### ISSUE TITLE
Add option 'first'  for freq/time_index to summary methods

### ISSUE THREAD

**Issue by asnyv** [equinor/fmu-ensemble#133]
Option `last`  already exists, an option `first` can be useful to e.g. check initial values without further filtering.

**Comment by berland** [comment]
https://github.com/equinor/fmu-ensemble/issues/135 uncovered independently at the same time as doing review. Do you want to have a stab at that one too?

**Comment by asnyv** [comment]
> #135 uncovered independently at the same time as doing review. Do you want to have a stab at that one too?

I can take a look 👍
