### ISSUE TITLE
load_smry cannot handle time_index=None

### ISSUE THREAD

**Issue by asnyv** [equinor/fmu-ensemble#142]
`load_smry`  with `time_index=None` crashes as `time_index_arg` is referenced before assignment in `realization.py`. (Checks are only performed on whether `time_index`  is a `list` or a `str`). The default for an `EnsembleSet.load_smry()` is `time_index=None`, hence this call crashes unless `time_index` is specifically set to a different value. 

Two solutions: 
- Disallow `None` as time_index for all `load_smry` and set the default in `EnsembleSet` to `raw` as in `ScratchEnsemble`
- Have an `else` statement similar to how it is solved in `get_smry`. Will require handling of the `time_index_path` in the the different `load_smry` cases (as `None` is not a string). Best solution might be to set it to `raw` if `time_index=None`, as the `raw` currently has the behavior that is expected from `None`, and would therefore be equal if both are called.

**Comment by berland** [comment]
I suggest solution 2 **and** setting the default for `time_index` to `raw` in `EnsembleSet.load_smry()`

**Comment by asnyv** [comment]
I am fine with that. In that case: What do we do if it is not a `str`, `list` or `None`? Raise `ValueError`? (as a final `else`). `get_smry` also just assumes that it is `None` if it is not `list` or `str`, but it is a bit dirty to not check it in my opinion.

**Comment by berland** [comment]
Perhaps raise `TypeError`?

**Comment by asnyv** [comment]
👍 Yes, probably better when we don't validate other than on type
