### ISSUE TITLE
Skip pre-gathering smry keys in ensemble get_smry_meta

### ISSUE THREAD

**Issue by asnyv** [equinor/fmu-ensemble#203]
The `get_smrykeys()` to gather the full set of keys is pretty much as heavy as the loop you do to actually get the metadata. Better to skip it and loop over all realizations to update the meta dict.
https://github.com/equinor/fmu-ensemble/blob/82cf5fa4b76a4f0c1c39548bff91eff387e92e33/src/fmu/ensemble/ensemble.py#L630-L645

**Comment by berland** [comment]
#205 will take a different approach, by only looking at already available dataframe data in `get_smry_meta()`
