### ISSUE TITLE
Possible segfault when reading summary data

### ISSUE THREAD

**Issue by oyvindeide** [equinor/fmu-ensemble#241]
Got a report of a user reading summary data, which most likely segfaulted, and took down the model, only trace I currently have is a the final log statement:
```
fmu.ensemble.ensemble - ThreadPoolExecutor-9_0 - INFO - Loading smry from realization 1
```

**Comment by eivindjahren** [comment]
Could be related to https://github.com/equinor/resdata/issues/945

**Comment by oyvindeide** [comment]
Could be, but was ran with 2020.2, so then the same problem has to be present in that version as well.

**Comment by oyvindeide** [comment]
Turns out it ran out of memory, and did not exit gracefully.
