### ISSUE TITLE
ecl2df has been renamed to res2df

### ISSUE THREAD

**Issue by eivindjahren** [equinor/fmu-ensemble#243]
The import https://github.com/equinor/fmu-ensemble/blob/ab3f4d7c02328352d8c64fdc70ca390749412bbf/src/fmu/ensemble/realization.py#L37 should be changed to `res2df` and `ecl2df.EclFiles` is now `res2df.ResFiles`.

**Comment by eivindjahren** [comment]
@asnyv any update on this?

**Comment by asnyv** [comment]
> @asnyv any update on this?

except that I had completely forgotten about it: Not until now 🤷‍♂️

Updated the PR now, tests are green. 
But I must admit it is the "lazy version": search, replace and hope that tests catches any issue. 
Have not gone through every single file manually.
