### ISSUE TITLE
Remove `watchdog` as dependency?

### ISSUE THREAD

**Issue by anders-kiaer** [equinor/fmu-ensemble#30]
On Python3, `pip install watchdog` appears to break hot reloading in e.g. dash/flask/webviz.

In addition, it looks like it is only defined in [the dependencies and not used](https://github.com/equinor/fmu-ensemble/search?q=watchdog&unscoped_q=watchdog).

**Comment by berland** [comment]
Yes, please remove. It has only been in use for some prototypes on STATUS file reloading.
