### ISSUE TITLE
Add dictionary for metadata to ensembles

### ISSUE THREAD

**Issue by berland** [equinor/fmu-ensemble#53]
Some applications need to associate a dictionary of metadata to ensembles.

This probably has to be a class member, typically initialized from a yaml file.

Should `__init__` support it, or should we require an extra function call to set it.

It requires support in virtual_ensembles, and in to/from_disk.

Should it be reset to None in EnsembleCombinations?

Should there be a default filename that can be looked for? A filename in use is `share/runinfo/runinfo.yaml` relative to the ensemble root.

**Comment by berland** [comment]
Suggests to use `add_manifest()` as a function in the Ensemble object. In disk-dumped virtual ensembles it should be named `_manifest.yml`

**Comment by perolavsvendsen** [comment]
Suggest that default filename to look for could/should be `share/manifest/manifest.yml`

**Comment by berland** [comment]
First PR will not include reading a default manifest file. 

Not sure if this library should be the first to define a manifest standard, or if users should define it first, by always setting the manifest to a standardized filename upon ensemble initialization.
