### ISSUE TITLE
Coupling to ecl2df

### ISSUE THREAD

**Issue by berland** [equinor/fmu-ensemble#70]
There should be some coupling to ecl2df (https://github.com/equinor/ecl2df) to facilitate easy callbacks from fmu-ensemble. 

At least, the realization objects should provide an `ecl2df.EclFiles` object on request.

**Comment by berland** [comment]
Not sure if ecl2df should be a requirement for fmu-ensemble, perhaps only optional, due to the extra difficulties imposed compiling opm-common + sunbeam for it to roll.

**Comment by anders-kiaer** [comment]
> Not sure if ecl2df should be a requirement for fmu-ensemble, perhaps only optional, due to the extra difficulties imposed compiling opm-common + sunbeam for it to roll.

Related to https://github.com/OPM/opm-common/issues/1210
